nodeLinker: hoisted
shamefullyHoist: true
allowBuilds:
  "@shopify/react-native-skia": true
  esbuild: true
minimumReleaseAgeExclude:
  - expo-notifications@57.0.17
  - '@expo/cli@57.0.22'
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo@57.0.20
  - '@expo/ui@57.0.16'
  - expo-router@57.0.19
